CREATE TABLE [dbo].[NOME_PACIENTE] (
    [ID_CONSULTA]   INT          NOT NULL IDENTITY,
    [NOME_PACIENTE] VARCHAR (35) NULL,
    [NOME_MEDICO]   VARCHAR (35) NULL,
    [DATA]          DATE         NULL,
    [HORARIO]       TIME (7)     NULL,
    PRIMARY KEY CLUSTERED ([ID_CONSULTA] ASC)
);

